import ProductDetails from '@/Component/Allproducts/ProductDetails';
import React from 'react';
export const metadata = {
  title: "Product Details",
  description: "Generated by create next app",
};
const Productdetails = () => {
    return (
        <div>
          <ProductDetails></ProductDetails>
        </div>
    );
};

export default Productdetails;